import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { AudioFormat } from "../src/lib/ffmpeg";
import type { AudioConverterPageConfig } from "../src/lib/audio/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");

const VIDEO_FORMATS = new Set([
  "mp4",
  "mov",
  "mkv",
  "webm",
  "avi",
  "mpeg",
  "flv",
  "wmv",
  "3gp",
  "m4v",
]);

const AUDIO_OUTPUTS = new Set([
  "wav",
  "mp3",
  "aac",
  "m4a",
  "flac",
  "ogg",
  "opus",
  "aiff",
]);

function formatLabel(format: string): string {
  return format.toUpperCase();
}

function parseCombos(markdown: string): Array<[string, string]> {
  const pairs: Array<[string, string]> = [];

  for (const line of markdown.split("\n")) {
    const match = line.match(/^- ([a-z0-9]+),([a-z0-9]+)$/);
    if (match) {
      pairs.push([match[1], match[2]]);
    }
  }

  return pairs;
}

function buildConfig(input: string, output: string): AudioConverterPageConfig {
  const slug = `${input}-to-${output}`;
  const inputLabel = formatLabel(input);
  const outputLabel = formatLabel(output);
  const defaultFormat = output as AudioFormat;
  const ogUrl = `https://luma.pub/audio/${slug}`;

  if (input === output) {
    return {
      slug,
      defaultFormat,
      title: `${inputLabel} Re-encoder — Free, No Upload | Luma`,
      description: `Re-encode ${inputLabel} online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.`,
      h1: `Re-encode ${inputLabel}.`,
      subtitle:
        "Change bitrate, sample rate, and channels — free, private, no upload required.",
      ogUrl,
      jsonLdName: `${inputLabel} Re-encoder`,
    };
  }

  if (VIDEO_FORMATS.has(input)) {
    return {
      slug,
      defaultFormat,
      title: `${inputLabel} to ${outputLabel} Converter — Free, No Upload | Luma`,
      description: `Convert ${inputLabel} to ${outputLabel} online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.`,
      h1: `Convert ${inputLabel} to ${outputLabel}.`,
      subtitle:
        "Extract audio from video files — free, private, no upload required.",
      ogUrl,
      jsonLdName: `${inputLabel} to ${outputLabel} Converter`,
    };
  }

  return {
    slug,
    defaultFormat,
    title: `${inputLabel} to ${outputLabel} Converter — Free, No Upload | Luma`,
    description: `Convert ${inputLabel} to ${outputLabel} online for free. No upload needed — runs entirely in your browser.`,
    h1: `Convert ${inputLabel} to ${outputLabel}.`,
    subtitle: "Convert audio files online — free, private, no upload required.",
    ogUrl,
    jsonLdName: `${inputLabel} to ${outputLabel} Converter`,
  };
}

function generate(): void {
  const sourcePath = join(ROOT, "docs/audio-combos.md");
  const outputPath = join(ROOT, "src/lib/audio/audioConverterCombos.ts");
  const markdown = readFileSync(sourcePath, "utf-8");
  const pairs = parseCombos(markdown);

  const configs = pairs.map(([input, output]) => {
    if (!AUDIO_OUTPUTS.has(output)) {
      throw new Error(`Unsupported output format: ${output}`);
    }
    return buildConfig(input, output);
  });

  const fileContents = `import type { AudioConverterPageConfig } from "@/lib/audio/types";

// Generated by scripts/generate-audio-combos.ts — do not edit manually.
// Re-run: cd site && pnpm dlx tsx scripts/generate-audio-combos.ts

export const AUDIO_CONVERTER_COMBOS: AudioConverterPageConfig[] = ${JSON.stringify(configs, null, 2)};
`;

  writeFileSync(outputPath, fileContents, "utf-8");
  console.log(`Wrote ${configs.length} combos to ${outputPath}`);
}

generate();
