import type { AudioConverterPageConfig } from "@/lib/audio/types";

// Generated by scripts/generate-audio-combos.ts — do not edit manually.
// Re-run: cd site && pnpm dlx tsx scripts/generate-audio-combos.ts

export const AUDIO_CONVERTER_COMBOS: AudioConverterPageConfig[] = [
  {
    "slug": "mp4-to-wav",
    "defaultFormat": "wav",
    "title": "MP4 to WAV Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-wav",
    "jsonLdName": "MP4 to WAV Converter"
  },
  {
    "slug": "mp4-to-mp3",
    "defaultFormat": "mp3",
    "title": "MP4 to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-mp3",
    "jsonLdName": "MP4 to MP3 Converter"
  },
  {
    "slug": "mp4-to-aac",
    "defaultFormat": "aac",
    "title": "MP4 to AAC Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-aac",
    "jsonLdName": "MP4 to AAC Converter"
  },
  {
    "slug": "mp4-to-m4a",
    "defaultFormat": "m4a",
    "title": "MP4 to M4A Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-m4a",
    "jsonLdName": "MP4 to M4A Converter"
  },
  {
    "slug": "mp4-to-flac",
    "defaultFormat": "flac",
    "title": "MP4 to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-flac",
    "jsonLdName": "MP4 to FLAC Converter"
  },
  {
    "slug": "mp4-to-ogg",
    "defaultFormat": "ogg",
    "title": "MP4 to OGG Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-ogg",
    "jsonLdName": "MP4 to OGG Converter"
  },
  {
    "slug": "mp4-to-opus",
    "defaultFormat": "opus",
    "title": "MP4 to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-opus",
    "jsonLdName": "MP4 to OPUS Converter"
  },
  {
    "slug": "mp4-to-aiff",
    "defaultFormat": "aiff",
    "title": "MP4 to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert MP4 to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MP4 to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp4-to-aiff",
    "jsonLdName": "MP4 to AIFF Converter"
  },
  {
    "slug": "mov-to-wav",
    "defaultFormat": "wav",
    "title": "MOV to WAV Converter — Free, No Upload | Luma",
    "description": "Convert MOV to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-wav",
    "jsonLdName": "MOV to WAV Converter"
  },
  {
    "slug": "mov-to-mp3",
    "defaultFormat": "mp3",
    "title": "MOV to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert MOV to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-mp3",
    "jsonLdName": "MOV to MP3 Converter"
  },
  {
    "slug": "mov-to-aac",
    "defaultFormat": "aac",
    "title": "MOV to AAC Converter — Free, No Upload | Luma",
    "description": "Convert MOV to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-aac",
    "jsonLdName": "MOV to AAC Converter"
  },
  {
    "slug": "mov-to-m4a",
    "defaultFormat": "m4a",
    "title": "MOV to M4A Converter — Free, No Upload | Luma",
    "description": "Convert MOV to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-m4a",
    "jsonLdName": "MOV to M4A Converter"
  },
  {
    "slug": "mov-to-flac",
    "defaultFormat": "flac",
    "title": "MOV to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert MOV to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-flac",
    "jsonLdName": "MOV to FLAC Converter"
  },
  {
    "slug": "mov-to-ogg",
    "defaultFormat": "ogg",
    "title": "MOV to OGG Converter — Free, No Upload | Luma",
    "description": "Convert MOV to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-ogg",
    "jsonLdName": "MOV to OGG Converter"
  },
  {
    "slug": "mov-to-opus",
    "defaultFormat": "opus",
    "title": "MOV to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert MOV to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-opus",
    "jsonLdName": "MOV to OPUS Converter"
  },
  {
    "slug": "mov-to-aiff",
    "defaultFormat": "aiff",
    "title": "MOV to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert MOV to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MOV to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mov-to-aiff",
    "jsonLdName": "MOV to AIFF Converter"
  },
  {
    "slug": "mkv-to-wav",
    "defaultFormat": "wav",
    "title": "MKV to WAV Converter — Free, No Upload | Luma",
    "description": "Convert MKV to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-wav",
    "jsonLdName": "MKV to WAV Converter"
  },
  {
    "slug": "mkv-to-mp3",
    "defaultFormat": "mp3",
    "title": "MKV to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert MKV to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-mp3",
    "jsonLdName": "MKV to MP3 Converter"
  },
  {
    "slug": "mkv-to-aac",
    "defaultFormat": "aac",
    "title": "MKV to AAC Converter — Free, No Upload | Luma",
    "description": "Convert MKV to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-aac",
    "jsonLdName": "MKV to AAC Converter"
  },
  {
    "slug": "mkv-to-m4a",
    "defaultFormat": "m4a",
    "title": "MKV to M4A Converter — Free, No Upload | Luma",
    "description": "Convert MKV to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-m4a",
    "jsonLdName": "MKV to M4A Converter"
  },
  {
    "slug": "mkv-to-flac",
    "defaultFormat": "flac",
    "title": "MKV to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert MKV to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-flac",
    "jsonLdName": "MKV to FLAC Converter"
  },
  {
    "slug": "mkv-to-ogg",
    "defaultFormat": "ogg",
    "title": "MKV to OGG Converter — Free, No Upload | Luma",
    "description": "Convert MKV to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-ogg",
    "jsonLdName": "MKV to OGG Converter"
  },
  {
    "slug": "mkv-to-opus",
    "defaultFormat": "opus",
    "title": "MKV to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert MKV to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-opus",
    "jsonLdName": "MKV to OPUS Converter"
  },
  {
    "slug": "mkv-to-aiff",
    "defaultFormat": "aiff",
    "title": "MKV to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert MKV to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MKV to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mkv-to-aiff",
    "jsonLdName": "MKV to AIFF Converter"
  },
  {
    "slug": "webm-to-wav",
    "defaultFormat": "wav",
    "title": "WEBM to WAV Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-wav",
    "jsonLdName": "WEBM to WAV Converter"
  },
  {
    "slug": "webm-to-mp3",
    "defaultFormat": "mp3",
    "title": "WEBM to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-mp3",
    "jsonLdName": "WEBM to MP3 Converter"
  },
  {
    "slug": "webm-to-aac",
    "defaultFormat": "aac",
    "title": "WEBM to AAC Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-aac",
    "jsonLdName": "WEBM to AAC Converter"
  },
  {
    "slug": "webm-to-m4a",
    "defaultFormat": "m4a",
    "title": "WEBM to M4A Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-m4a",
    "jsonLdName": "WEBM to M4A Converter"
  },
  {
    "slug": "webm-to-flac",
    "defaultFormat": "flac",
    "title": "WEBM to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-flac",
    "jsonLdName": "WEBM to FLAC Converter"
  },
  {
    "slug": "webm-to-ogg",
    "defaultFormat": "ogg",
    "title": "WEBM to OGG Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-ogg",
    "jsonLdName": "WEBM to OGG Converter"
  },
  {
    "slug": "webm-to-opus",
    "defaultFormat": "opus",
    "title": "WEBM to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-opus",
    "jsonLdName": "WEBM to OPUS Converter"
  },
  {
    "slug": "webm-to-aiff",
    "defaultFormat": "aiff",
    "title": "WEBM to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert WEBM to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WEBM to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/webm-to-aiff",
    "jsonLdName": "WEBM to AIFF Converter"
  },
  {
    "slug": "avi-to-wav",
    "defaultFormat": "wav",
    "title": "AVI to WAV Converter — Free, No Upload | Luma",
    "description": "Convert AVI to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-wav",
    "jsonLdName": "AVI to WAV Converter"
  },
  {
    "slug": "avi-to-mp3",
    "defaultFormat": "mp3",
    "title": "AVI to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert AVI to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-mp3",
    "jsonLdName": "AVI to MP3 Converter"
  },
  {
    "slug": "avi-to-aac",
    "defaultFormat": "aac",
    "title": "AVI to AAC Converter — Free, No Upload | Luma",
    "description": "Convert AVI to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-aac",
    "jsonLdName": "AVI to AAC Converter"
  },
  {
    "slug": "avi-to-m4a",
    "defaultFormat": "m4a",
    "title": "AVI to M4A Converter — Free, No Upload | Luma",
    "description": "Convert AVI to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-m4a",
    "jsonLdName": "AVI to M4A Converter"
  },
  {
    "slug": "avi-to-flac",
    "defaultFormat": "flac",
    "title": "AVI to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert AVI to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-flac",
    "jsonLdName": "AVI to FLAC Converter"
  },
  {
    "slug": "avi-to-ogg",
    "defaultFormat": "ogg",
    "title": "AVI to OGG Converter — Free, No Upload | Luma",
    "description": "Convert AVI to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-ogg",
    "jsonLdName": "AVI to OGG Converter"
  },
  {
    "slug": "avi-to-opus",
    "defaultFormat": "opus",
    "title": "AVI to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert AVI to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-opus",
    "jsonLdName": "AVI to OPUS Converter"
  },
  {
    "slug": "avi-to-aiff",
    "defaultFormat": "aiff",
    "title": "AVI to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert AVI to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert AVI to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/avi-to-aiff",
    "jsonLdName": "AVI to AIFF Converter"
  },
  {
    "slug": "mpeg-to-wav",
    "defaultFormat": "wav",
    "title": "MPEG to WAV Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-wav",
    "jsonLdName": "MPEG to WAV Converter"
  },
  {
    "slug": "mpeg-to-mp3",
    "defaultFormat": "mp3",
    "title": "MPEG to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-mp3",
    "jsonLdName": "MPEG to MP3 Converter"
  },
  {
    "slug": "mpeg-to-aac",
    "defaultFormat": "aac",
    "title": "MPEG to AAC Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-aac",
    "jsonLdName": "MPEG to AAC Converter"
  },
  {
    "slug": "mpeg-to-m4a",
    "defaultFormat": "m4a",
    "title": "MPEG to M4A Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-m4a",
    "jsonLdName": "MPEG to M4A Converter"
  },
  {
    "slug": "mpeg-to-flac",
    "defaultFormat": "flac",
    "title": "MPEG to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-flac",
    "jsonLdName": "MPEG to FLAC Converter"
  },
  {
    "slug": "mpeg-to-ogg",
    "defaultFormat": "ogg",
    "title": "MPEG to OGG Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-ogg",
    "jsonLdName": "MPEG to OGG Converter"
  },
  {
    "slug": "mpeg-to-opus",
    "defaultFormat": "opus",
    "title": "MPEG to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-opus",
    "jsonLdName": "MPEG to OPUS Converter"
  },
  {
    "slug": "mpeg-to-aiff",
    "defaultFormat": "aiff",
    "title": "MPEG to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert MPEG to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert MPEG to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mpeg-to-aiff",
    "jsonLdName": "MPEG to AIFF Converter"
  },
  {
    "slug": "flv-to-wav",
    "defaultFormat": "wav",
    "title": "FLV to WAV Converter — Free, No Upload | Luma",
    "description": "Convert FLV to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-wav",
    "jsonLdName": "FLV to WAV Converter"
  },
  {
    "slug": "flv-to-mp3",
    "defaultFormat": "mp3",
    "title": "FLV to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert FLV to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-mp3",
    "jsonLdName": "FLV to MP3 Converter"
  },
  {
    "slug": "flv-to-aac",
    "defaultFormat": "aac",
    "title": "FLV to AAC Converter — Free, No Upload | Luma",
    "description": "Convert FLV to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-aac",
    "jsonLdName": "FLV to AAC Converter"
  },
  {
    "slug": "flv-to-m4a",
    "defaultFormat": "m4a",
    "title": "FLV to M4A Converter — Free, No Upload | Luma",
    "description": "Convert FLV to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-m4a",
    "jsonLdName": "FLV to M4A Converter"
  },
  {
    "slug": "flv-to-flac",
    "defaultFormat": "flac",
    "title": "FLV to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert FLV to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-flac",
    "jsonLdName": "FLV to FLAC Converter"
  },
  {
    "slug": "flv-to-ogg",
    "defaultFormat": "ogg",
    "title": "FLV to OGG Converter — Free, No Upload | Luma",
    "description": "Convert FLV to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-ogg",
    "jsonLdName": "FLV to OGG Converter"
  },
  {
    "slug": "flv-to-opus",
    "defaultFormat": "opus",
    "title": "FLV to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert FLV to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-opus",
    "jsonLdName": "FLV to OPUS Converter"
  },
  {
    "slug": "flv-to-aiff",
    "defaultFormat": "aiff",
    "title": "FLV to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert FLV to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert FLV to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flv-to-aiff",
    "jsonLdName": "FLV to AIFF Converter"
  },
  {
    "slug": "wmv-to-wav",
    "defaultFormat": "wav",
    "title": "WMV to WAV Converter — Free, No Upload | Luma",
    "description": "Convert WMV to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-wav",
    "jsonLdName": "WMV to WAV Converter"
  },
  {
    "slug": "wmv-to-mp3",
    "defaultFormat": "mp3",
    "title": "WMV to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert WMV to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-mp3",
    "jsonLdName": "WMV to MP3 Converter"
  },
  {
    "slug": "wmv-to-aac",
    "defaultFormat": "aac",
    "title": "WMV to AAC Converter — Free, No Upload | Luma",
    "description": "Convert WMV to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-aac",
    "jsonLdName": "WMV to AAC Converter"
  },
  {
    "slug": "wmv-to-m4a",
    "defaultFormat": "m4a",
    "title": "WMV to M4A Converter — Free, No Upload | Luma",
    "description": "Convert WMV to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-m4a",
    "jsonLdName": "WMV to M4A Converter"
  },
  {
    "slug": "wmv-to-flac",
    "defaultFormat": "flac",
    "title": "WMV to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert WMV to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-flac",
    "jsonLdName": "WMV to FLAC Converter"
  },
  {
    "slug": "wmv-to-ogg",
    "defaultFormat": "ogg",
    "title": "WMV to OGG Converter — Free, No Upload | Luma",
    "description": "Convert WMV to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-ogg",
    "jsonLdName": "WMV to OGG Converter"
  },
  {
    "slug": "wmv-to-opus",
    "defaultFormat": "opus",
    "title": "WMV to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert WMV to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-opus",
    "jsonLdName": "WMV to OPUS Converter"
  },
  {
    "slug": "wmv-to-aiff",
    "defaultFormat": "aiff",
    "title": "WMV to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert WMV to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert WMV to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wmv-to-aiff",
    "jsonLdName": "WMV to AIFF Converter"
  },
  {
    "slug": "3gp-to-wav",
    "defaultFormat": "wav",
    "title": "3GP to WAV Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-wav",
    "jsonLdName": "3GP to WAV Converter"
  },
  {
    "slug": "3gp-to-mp3",
    "defaultFormat": "mp3",
    "title": "3GP to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-mp3",
    "jsonLdName": "3GP to MP3 Converter"
  },
  {
    "slug": "3gp-to-aac",
    "defaultFormat": "aac",
    "title": "3GP to AAC Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-aac",
    "jsonLdName": "3GP to AAC Converter"
  },
  {
    "slug": "3gp-to-m4a",
    "defaultFormat": "m4a",
    "title": "3GP to M4A Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-m4a",
    "jsonLdName": "3GP to M4A Converter"
  },
  {
    "slug": "3gp-to-flac",
    "defaultFormat": "flac",
    "title": "3GP to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-flac",
    "jsonLdName": "3GP to FLAC Converter"
  },
  {
    "slug": "3gp-to-ogg",
    "defaultFormat": "ogg",
    "title": "3GP to OGG Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-ogg",
    "jsonLdName": "3GP to OGG Converter"
  },
  {
    "slug": "3gp-to-opus",
    "defaultFormat": "opus",
    "title": "3GP to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-opus",
    "jsonLdName": "3GP to OPUS Converter"
  },
  {
    "slug": "3gp-to-aiff",
    "defaultFormat": "aiff",
    "title": "3GP to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert 3GP to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert 3GP to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/3gp-to-aiff",
    "jsonLdName": "3GP to AIFF Converter"
  },
  {
    "slug": "m4v-to-wav",
    "defaultFormat": "wav",
    "title": "M4V to WAV Converter — Free, No Upload | Luma",
    "description": "Convert M4V to WAV online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to WAV.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-wav",
    "jsonLdName": "M4V to WAV Converter"
  },
  {
    "slug": "m4v-to-mp3",
    "defaultFormat": "mp3",
    "title": "M4V to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert M4V to MP3 online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to MP3.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-mp3",
    "jsonLdName": "M4V to MP3 Converter"
  },
  {
    "slug": "m4v-to-aac",
    "defaultFormat": "aac",
    "title": "M4V to AAC Converter — Free, No Upload | Luma",
    "description": "Convert M4V to AAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to AAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-aac",
    "jsonLdName": "M4V to AAC Converter"
  },
  {
    "slug": "m4v-to-m4a",
    "defaultFormat": "m4a",
    "title": "M4V to M4A Converter — Free, No Upload | Luma",
    "description": "Convert M4V to M4A online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to M4A.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-m4a",
    "jsonLdName": "M4V to M4A Converter"
  },
  {
    "slug": "m4v-to-flac",
    "defaultFormat": "flac",
    "title": "M4V to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert M4V to FLAC online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to FLAC.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-flac",
    "jsonLdName": "M4V to FLAC Converter"
  },
  {
    "slug": "m4v-to-ogg",
    "defaultFormat": "ogg",
    "title": "M4V to OGG Converter — Free, No Upload | Luma",
    "description": "Convert M4V to OGG online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to OGG.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-ogg",
    "jsonLdName": "M4V to OGG Converter"
  },
  {
    "slug": "m4v-to-opus",
    "defaultFormat": "opus",
    "title": "M4V to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert M4V to OPUS online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to OPUS.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-opus",
    "jsonLdName": "M4V to OPUS Converter"
  },
  {
    "slug": "m4v-to-aiff",
    "defaultFormat": "aiff",
    "title": "M4V to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert M4V to AIFF online for free. No upload needed — runs entirely in your browser. Extract high-quality audio from video files instantly.",
    "h1": "Convert M4V to AIFF.",
    "subtitle": "Extract audio from video files — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4v-to-aiff",
    "jsonLdName": "M4V to AIFF Converter"
  },
  {
    "slug": "mp3-to-wav",
    "defaultFormat": "wav",
    "title": "MP3 to WAV Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-wav",
    "jsonLdName": "MP3 to WAV Converter"
  },
  {
    "slug": "mp3-to-mp3",
    "defaultFormat": "mp3",
    "title": "MP3 Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode MP3 online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode MP3.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-mp3",
    "jsonLdName": "MP3 Re-encoder"
  },
  {
    "slug": "mp3-to-aac",
    "defaultFormat": "aac",
    "title": "MP3 to AAC Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-aac",
    "jsonLdName": "MP3 to AAC Converter"
  },
  {
    "slug": "mp3-to-m4a",
    "defaultFormat": "m4a",
    "title": "MP3 to M4A Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-m4a",
    "jsonLdName": "MP3 to M4A Converter"
  },
  {
    "slug": "mp3-to-flac",
    "defaultFormat": "flac",
    "title": "MP3 to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-flac",
    "jsonLdName": "MP3 to FLAC Converter"
  },
  {
    "slug": "mp3-to-ogg",
    "defaultFormat": "ogg",
    "title": "MP3 to OGG Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-ogg",
    "jsonLdName": "MP3 to OGG Converter"
  },
  {
    "slug": "mp3-to-opus",
    "defaultFormat": "opus",
    "title": "MP3 to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-opus",
    "jsonLdName": "MP3 to OPUS Converter"
  },
  {
    "slug": "mp3-to-aiff",
    "defaultFormat": "aiff",
    "title": "MP3 to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert MP3 to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert MP3 to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/mp3-to-aiff",
    "jsonLdName": "MP3 to AIFF Converter"
  },
  {
    "slug": "wav-to-wav",
    "defaultFormat": "wav",
    "title": "WAV Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode WAV online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode WAV.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-wav",
    "jsonLdName": "WAV Re-encoder"
  },
  {
    "slug": "wav-to-mp3",
    "defaultFormat": "mp3",
    "title": "WAV to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert WAV to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-mp3",
    "jsonLdName": "WAV to MP3 Converter"
  },
  {
    "slug": "wav-to-aac",
    "defaultFormat": "aac",
    "title": "WAV to AAC Converter — Free, No Upload | Luma",
    "description": "Convert WAV to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-aac",
    "jsonLdName": "WAV to AAC Converter"
  },
  {
    "slug": "wav-to-m4a",
    "defaultFormat": "m4a",
    "title": "WAV to M4A Converter — Free, No Upload | Luma",
    "description": "Convert WAV to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-m4a",
    "jsonLdName": "WAV to M4A Converter"
  },
  {
    "slug": "wav-to-flac",
    "defaultFormat": "flac",
    "title": "WAV to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert WAV to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-flac",
    "jsonLdName": "WAV to FLAC Converter"
  },
  {
    "slug": "wav-to-ogg",
    "defaultFormat": "ogg",
    "title": "WAV to OGG Converter — Free, No Upload | Luma",
    "description": "Convert WAV to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-ogg",
    "jsonLdName": "WAV to OGG Converter"
  },
  {
    "slug": "wav-to-opus",
    "defaultFormat": "opus",
    "title": "WAV to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert WAV to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-opus",
    "jsonLdName": "WAV to OPUS Converter"
  },
  {
    "slug": "wav-to-aiff",
    "defaultFormat": "aiff",
    "title": "WAV to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert WAV to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert WAV to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/wav-to-aiff",
    "jsonLdName": "WAV to AIFF Converter"
  },
  {
    "slug": "aac-to-wav",
    "defaultFormat": "wav",
    "title": "AAC to WAV Converter — Free, No Upload | Luma",
    "description": "Convert AAC to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-wav",
    "jsonLdName": "AAC to WAV Converter"
  },
  {
    "slug": "aac-to-mp3",
    "defaultFormat": "mp3",
    "title": "AAC to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert AAC to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-mp3",
    "jsonLdName": "AAC to MP3 Converter"
  },
  {
    "slug": "aac-to-aac",
    "defaultFormat": "aac",
    "title": "AAC Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode AAC online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode AAC.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-aac",
    "jsonLdName": "AAC Re-encoder"
  },
  {
    "slug": "aac-to-m4a",
    "defaultFormat": "m4a",
    "title": "AAC to M4A Converter — Free, No Upload | Luma",
    "description": "Convert AAC to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-m4a",
    "jsonLdName": "AAC to M4A Converter"
  },
  {
    "slug": "aac-to-flac",
    "defaultFormat": "flac",
    "title": "AAC to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert AAC to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-flac",
    "jsonLdName": "AAC to FLAC Converter"
  },
  {
    "slug": "aac-to-ogg",
    "defaultFormat": "ogg",
    "title": "AAC to OGG Converter — Free, No Upload | Luma",
    "description": "Convert AAC to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-ogg",
    "jsonLdName": "AAC to OGG Converter"
  },
  {
    "slug": "aac-to-opus",
    "defaultFormat": "opus",
    "title": "AAC to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert AAC to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-opus",
    "jsonLdName": "AAC to OPUS Converter"
  },
  {
    "slug": "aac-to-aiff",
    "defaultFormat": "aiff",
    "title": "AAC to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert AAC to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AAC to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aac-to-aiff",
    "jsonLdName": "AAC to AIFF Converter"
  },
  {
    "slug": "m4a-to-wav",
    "defaultFormat": "wav",
    "title": "M4A to WAV Converter — Free, No Upload | Luma",
    "description": "Convert M4A to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-wav",
    "jsonLdName": "M4A to WAV Converter"
  },
  {
    "slug": "m4a-to-mp3",
    "defaultFormat": "mp3",
    "title": "M4A to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert M4A to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-mp3",
    "jsonLdName": "M4A to MP3 Converter"
  },
  {
    "slug": "m4a-to-aac",
    "defaultFormat": "aac",
    "title": "M4A to AAC Converter — Free, No Upload | Luma",
    "description": "Convert M4A to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-aac",
    "jsonLdName": "M4A to AAC Converter"
  },
  {
    "slug": "m4a-to-m4a",
    "defaultFormat": "m4a",
    "title": "M4A Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode M4A online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode M4A.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-m4a",
    "jsonLdName": "M4A Re-encoder"
  },
  {
    "slug": "m4a-to-flac",
    "defaultFormat": "flac",
    "title": "M4A to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert M4A to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-flac",
    "jsonLdName": "M4A to FLAC Converter"
  },
  {
    "slug": "m4a-to-ogg",
    "defaultFormat": "ogg",
    "title": "M4A to OGG Converter — Free, No Upload | Luma",
    "description": "Convert M4A to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-ogg",
    "jsonLdName": "M4A to OGG Converter"
  },
  {
    "slug": "m4a-to-opus",
    "defaultFormat": "opus",
    "title": "M4A to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert M4A to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-opus",
    "jsonLdName": "M4A to OPUS Converter"
  },
  {
    "slug": "m4a-to-aiff",
    "defaultFormat": "aiff",
    "title": "M4A to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert M4A to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert M4A to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/m4a-to-aiff",
    "jsonLdName": "M4A to AIFF Converter"
  },
  {
    "slug": "flac-to-wav",
    "defaultFormat": "wav",
    "title": "FLAC to WAV Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-wav",
    "jsonLdName": "FLAC to WAV Converter"
  },
  {
    "slug": "flac-to-mp3",
    "defaultFormat": "mp3",
    "title": "FLAC to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-mp3",
    "jsonLdName": "FLAC to MP3 Converter"
  },
  {
    "slug": "flac-to-aac",
    "defaultFormat": "aac",
    "title": "FLAC to AAC Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-aac",
    "jsonLdName": "FLAC to AAC Converter"
  },
  {
    "slug": "flac-to-m4a",
    "defaultFormat": "m4a",
    "title": "FLAC to M4A Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-m4a",
    "jsonLdName": "FLAC to M4A Converter"
  },
  {
    "slug": "flac-to-flac",
    "defaultFormat": "flac",
    "title": "FLAC Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode FLAC online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode FLAC.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-flac",
    "jsonLdName": "FLAC Re-encoder"
  },
  {
    "slug": "flac-to-ogg",
    "defaultFormat": "ogg",
    "title": "FLAC to OGG Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-ogg",
    "jsonLdName": "FLAC to OGG Converter"
  },
  {
    "slug": "flac-to-opus",
    "defaultFormat": "opus",
    "title": "FLAC to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-opus",
    "jsonLdName": "FLAC to OPUS Converter"
  },
  {
    "slug": "flac-to-aiff",
    "defaultFormat": "aiff",
    "title": "FLAC to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert FLAC to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert FLAC to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/flac-to-aiff",
    "jsonLdName": "FLAC to AIFF Converter"
  },
  {
    "slug": "ogg-to-wav",
    "defaultFormat": "wav",
    "title": "OGG to WAV Converter — Free, No Upload | Luma",
    "description": "Convert OGG to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-wav",
    "jsonLdName": "OGG to WAV Converter"
  },
  {
    "slug": "ogg-to-mp3",
    "defaultFormat": "mp3",
    "title": "OGG to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert OGG to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-mp3",
    "jsonLdName": "OGG to MP3 Converter"
  },
  {
    "slug": "ogg-to-aac",
    "defaultFormat": "aac",
    "title": "OGG to AAC Converter — Free, No Upload | Luma",
    "description": "Convert OGG to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-aac",
    "jsonLdName": "OGG to AAC Converter"
  },
  {
    "slug": "ogg-to-m4a",
    "defaultFormat": "m4a",
    "title": "OGG to M4A Converter — Free, No Upload | Luma",
    "description": "Convert OGG to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-m4a",
    "jsonLdName": "OGG to M4A Converter"
  },
  {
    "slug": "ogg-to-flac",
    "defaultFormat": "flac",
    "title": "OGG to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert OGG to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-flac",
    "jsonLdName": "OGG to FLAC Converter"
  },
  {
    "slug": "ogg-to-ogg",
    "defaultFormat": "ogg",
    "title": "OGG Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode OGG online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode OGG.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-ogg",
    "jsonLdName": "OGG Re-encoder"
  },
  {
    "slug": "ogg-to-opus",
    "defaultFormat": "opus",
    "title": "OGG to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert OGG to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-opus",
    "jsonLdName": "OGG to OPUS Converter"
  },
  {
    "slug": "ogg-to-aiff",
    "defaultFormat": "aiff",
    "title": "OGG to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert OGG to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OGG to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/ogg-to-aiff",
    "jsonLdName": "OGG to AIFF Converter"
  },
  {
    "slug": "opus-to-wav",
    "defaultFormat": "wav",
    "title": "OPUS to WAV Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-wav",
    "jsonLdName": "OPUS to WAV Converter"
  },
  {
    "slug": "opus-to-mp3",
    "defaultFormat": "mp3",
    "title": "OPUS to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-mp3",
    "jsonLdName": "OPUS to MP3 Converter"
  },
  {
    "slug": "opus-to-aac",
    "defaultFormat": "aac",
    "title": "OPUS to AAC Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-aac",
    "jsonLdName": "OPUS to AAC Converter"
  },
  {
    "slug": "opus-to-m4a",
    "defaultFormat": "m4a",
    "title": "OPUS to M4A Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-m4a",
    "jsonLdName": "OPUS to M4A Converter"
  },
  {
    "slug": "opus-to-flac",
    "defaultFormat": "flac",
    "title": "OPUS to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-flac",
    "jsonLdName": "OPUS to FLAC Converter"
  },
  {
    "slug": "opus-to-ogg",
    "defaultFormat": "ogg",
    "title": "OPUS to OGG Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-ogg",
    "jsonLdName": "OPUS to OGG Converter"
  },
  {
    "slug": "opus-to-opus",
    "defaultFormat": "opus",
    "title": "OPUS Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode OPUS online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode OPUS.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-opus",
    "jsonLdName": "OPUS Re-encoder"
  },
  {
    "slug": "opus-to-aiff",
    "defaultFormat": "aiff",
    "title": "OPUS to AIFF Converter — Free, No Upload | Luma",
    "description": "Convert OPUS to AIFF online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert OPUS to AIFF.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/opus-to-aiff",
    "jsonLdName": "OPUS to AIFF Converter"
  },
  {
    "slug": "aiff-to-wav",
    "defaultFormat": "wav",
    "title": "AIFF to WAV Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to WAV online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to WAV.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-wav",
    "jsonLdName": "AIFF to WAV Converter"
  },
  {
    "slug": "aiff-to-mp3",
    "defaultFormat": "mp3",
    "title": "AIFF to MP3 Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to MP3 online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to MP3.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-mp3",
    "jsonLdName": "AIFF to MP3 Converter"
  },
  {
    "slug": "aiff-to-aac",
    "defaultFormat": "aac",
    "title": "AIFF to AAC Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to AAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to AAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-aac",
    "jsonLdName": "AIFF to AAC Converter"
  },
  {
    "slug": "aiff-to-m4a",
    "defaultFormat": "m4a",
    "title": "AIFF to M4A Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to M4A online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to M4A.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-m4a",
    "jsonLdName": "AIFF to M4A Converter"
  },
  {
    "slug": "aiff-to-flac",
    "defaultFormat": "flac",
    "title": "AIFF to FLAC Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to FLAC online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to FLAC.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-flac",
    "jsonLdName": "AIFF to FLAC Converter"
  },
  {
    "slug": "aiff-to-ogg",
    "defaultFormat": "ogg",
    "title": "AIFF to OGG Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to OGG online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to OGG.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-ogg",
    "jsonLdName": "AIFF to OGG Converter"
  },
  {
    "slug": "aiff-to-opus",
    "defaultFormat": "opus",
    "title": "AIFF to OPUS Converter — Free, No Upload | Luma",
    "description": "Convert AIFF to OPUS online for free. No upload needed — runs entirely in your browser.",
    "h1": "Convert AIFF to OPUS.",
    "subtitle": "Convert audio files online — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-opus",
    "jsonLdName": "AIFF to OPUS Converter"
  },
  {
    "slug": "aiff-to-aiff",
    "defaultFormat": "aiff",
    "title": "AIFF Re-encoder — Free, No Upload | Luma",
    "description": "Re-encode AIFF online for free. Adjust bitrate, sample rate, and channels in your browser — no upload required.",
    "h1": "Re-encode AIFF.",
    "subtitle": "Change bitrate, sample rate, and channels — free, private, no upload required.",
    "ogUrl": "https://luma.pub/audio/aiff-to-aiff",
    "jsonLdName": "AIFF Re-encoder"
  }
];
